#!/usr/bin/env bash

eval "$(/opt/homebrew/bin/brew shellenv)"
brew install dotbot
git clone https://github.com/chriskacerguis/dotfiles.git ~/.dotfiles
dotbot -d ~/.dotfiles -c ~/.dotfiles/install.conf.yaml
